/** Social platform referrers. Matched against the referrer hostname. */
export const SOCIAL_PLATFORMS: Record<string, string> = {
  'facebook.': 'facebook',
  'fb.com': 'facebook',
  'fb.me': 'facebook',
  'l.facebook.': 'facebook',
  'lm.facebook.': 'facebook',
  'instagram.': 'instagram',
  'l.instagram.': 'instagram',
  'threads.net': 'threads',
  'threads.com': 'threads',
  'linkedin.': 'linkedin',
  'lnkd.in': 'linkedin',
  'twitter.': 'twitter',
  'x.com': 'twitter',
  't.co': 'twitter',
  'pinterest.': 'pinterest',
  'pin.it': 'pinterest',
  'tiktok.': 'tiktok',
  'reddit.': 'reddit',
  'youtube.': 'youtube',
  'youtu.be': 'youtube',
  'nextdoor.': 'nextdoor',
  'snapchat.': 'snapchat',
  'whatsapp.': 'whatsapp',
  'telegram.': 'telegram',
  't.me': 'telegram',
  'discord.': 'discord',
  'tumblr.': 'tumblr',
  'mastodon.': 'mastodon',
  'bsky.app': 'bluesky',
  'quora.': 'quora',
  'medium.com': 'medium',
};
